repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
        args: ["--severity=style", "--external-sources", "--check-sourced"]

  # Showcase for this repo's hook
  - repo: https://github.com/lu0/git-worktree-airflow
    rev: v1.1.3
    hooks:
      - id: airflow-worktree
        name: Update .airflowignore to load DAGs from worktree
        stages: [post-checkout]
        always_run: true
        verbose: true
